CP_CheckPassword = @0001
CP_WorldInfoRequest = @0002

CP_CheckUserLimit = @0005
CP_SelectWorld = @0009
CP_SelectCharacter =@000A
CP_MigrateIn = @000B
CP_CheckDuplicatedID = @000C
CP_CreateNewCharacter = @0011
CP_DeleteCharacter
CP_AliveAck = @0014
CP_ExceptionLog = @0015
CP_JMS_CheckGameGuardUpdated
CP_JMS_GetMapLogin = @001E

CP_UserTransferFieldRequest = @0021
CP_UserTransferChannelRequest = @0022
CP_UserMigrateToCashShopRequest = @0023
CP_UserMove = @0024
CP_UserSitRequest
CP_UserPortableChairSitRequest
CP_UserMeleeAttack
CP_UserShootAttack
CP_UserMagicAttack

CP_UserChat = @0031

CP_UserSelectNpc = @003A
CP_UserRemoteShopOpenRequest = @003B
CP_UserScriptMessageAnswer = @003C
CP_UserShopRequest = @003D
CP_UserTrunkRequest = @003E

CP_UserChangeSlotPositionRequest = @0049
CP_UserStatChangeItemUseRequest = @004A

CP_UserConsumeCashItemUseRequest = @0051

CP_UserPortalScrollUseRequest = @0058
CP_UserUpgradeItemUseRequest = @0059

CP_UserAbilityUpRequest
CP_UserAbilityMassUpRequest
CP_UserSkillUpRequest
CP_UserSkillUseRequest
CP_UserSkillCancelRequest
CP_UserSkillPrepareRequest
CP_UserDropMoneyRequest

CP_UserCharacterInfoRequest

CP_UserPortalScriptRequest = @006D
CP_UserPortalTeleportRequest = @006E


CP_FuncKeyMappedModified

CP_UserMigrateToITCRequest = @00A5

CP_DropPickUpRequest