CP_BEGIN_SOCKET
CP_CheckPassword = @0001
CP_AccountInfoRequest
CP_WorldInfoRequest
CP_CheckUserLimit = @0004
CP_SelectWorld = @0006
CP_LogoutWorld
CP_SelectCharacter = @0007
CP_MigrateIn = @0008
CP_CheckDuplicatedID = @0009
CP_CreateNewCharacter = @000E
CP_DeleteCharacter = @000F
CP_AliveAck = @0011
CP_ExceptionLog = @0012
CP_SecurityPacket
CP_END_SOCKET
CP_BEGIN_USER
CP_UserTransferFieldRequest = @001F
CP_UserTransferChannelRequest = @0020
CP_UserMigrateToCashShopRequest = @0021
CP_UserMove = @0022
CP_UserSitRequest = @0023
CP_UserPortableChairSitRequest = @0024
CP_UserMeleeAttack = @0025
CP_UserShootAttack = @0026
CP_UserMagicAttack = @0027
CP_UserBodyAttack = @0028
CP_UserHit = @0029
CP_UserChat = @002A
CP_UserADBoardClose = @002B
CP_UserActivateEffectItem
CP_UserMonsterBookSetCover
CP_UserSelectNpc = @0033
CP_UserRemoteShopOpenRequest = @0034
CP_UserScriptMessageAnswer = @0035

CP_UserShopRequest = @0037
CP_UserTrunkRequest = @0038
CP_UserEntrustedShopRequest
CP_UserParcelRequest = @003B
CP_ShopScannerRequest = @003C
CP_UserGatherItemRequest = @003F
CP_UserSortItemRequest = @0040
CP_UserChangeSlotPositionRequest = @0041
CP_UserStatChangeItemUseRequest = @0042
CP_UserStatChangeItemCancelRequest
CP_UserMobSummonItemUseRequest = @0045
CP_UserPetFoodItemUseRequest = @0046
CP_UserConsumeCashItemUseRequest = @0049
CP_UserBridleItemUseRequest
CP_UserSkillLearnItemUseRequest = @004C
CP_UserShopScannerItemUseRequest = @004D
CP_UserMapTransferItemUseRequest = @004E
CP_UserPortalScrollUseRequest = @004F
CP_UserUpgradeItemUseRequest = @0050
CP_UserAbilityUpRequest = @0051
CP_UserAbilityMassUpRequest = @0052
CP_UserChangeStatRequest = @0053
CP_UserSkillUpRequest = @0054
CP_UserSkillUseRequest = @0055
CP_UserSkillCancelRequest = @0056
CP_UserSkillPrepareRequest = @0057
CP_UserDropMoneyRequest = @0058
CP_UserGivePopularityRequest
CP_UserCharacterInfoRequest = @005B
CP_UserActivatePetRequest = @005C
CP_UserTemporaryStatUpdateRequest = @005D
CP_UserPortalScriptRequest = @005E
CP_UserPortalTeleportRequest = @005F
CP_UserMapTransferRequest
CP_UserQuestRequest
CP_UserExpUpItemUseRequest = @0089
CP_UserTempExpUseRequest = @008A
CP_GroupMessage
CP_Whisper
CP_Messenger
CP_MiniRoom
CP_PartyRequest
CP_Admin
CP_Log
CP_FriendRequest
CP_FuncKeyMappedModified = @007E
CP_RPSGame
CP_MarriageRequest
CP_UserMigrateToITCRequest = @0088
CP_END_USER
CP_BEGIN_PET
CP_PetMove
CP_PetAction
CP_PetInteractionRequest
CP_PetDropPickUpRequest
CP_PetStatChangeItemUseRequest
CP_PetUpdateExceptionListRequest
CP_END_PET
CP_BEGIN_SUMMONED
CP_SummonedMove
CP_SummonedAttack
CP_SummonedHit
CP_SummonedSkill
CP_Remove
CP_END_SUMMONED
CP_BEGIN_FIELD
CP_BEGIN_LIFEPOOL
CP_BEGIN_MOB
CP_MobMove = @00AF
CP_MobApplyCtrl = @00B0
CP_MobDropPickUpRequest
CP_MobHitByObstacle
CP_MobHitByMob
CP_MobSelfDestruct
CP_END_MOB
CP_BEGIN_NPC
CP_NpcMove = @00B8
CP_NpcSpecialAction
CP_END_NPC
CP_END_LIFEPOOL
CP_BEGIN_DROPPOOL
CP_DropPickUpRequest = @00BE
CP_END_DROPPOOL
CP_BEGIN_REACTORPOOL
CP_ReactorHit = @00C1
CP_ReactorTouch
CP_RequireFieldObstacleStatus
CP_END_REACTORPOOL
CP_BEGIN_EVENT_FIELD
CP_EventStart
CP_SnowBallHit
CP_SnowBallTouch
CP_CoconutHit
CP_TournamentMatchTable
CP_PulleyHit
CP_END_EVENT_FIELD
CP_CONTISTATE
CP_BEGIN_PARTY_MATCH
CP_INVITE_PARTY_MATCH
CP_CANCEL_INVITE_PARTY_MATCH
CP_END_PARTY_MATCH
CP_END_FIELD
CP_BEGIN_CASHSHOP
CP_CashShopChargeParamRequest
CP_CashShopQueryCashRequest
CP_CashShopCashItemRequest
CP_CashShopCheckCouponRequest
CP_CashShopGiftMateInfoRequest
CP_END_CASHSHOP
CP_BEGIN_ITC
CP_ITCChargeParamRequest
CP_ITCQueryCashRequest
CP_ITCItemRequest
CP_END_ITC
CP_BEGIN_MAPLETV
CP_MapleTVSendMessageRequest
CP_MapleTVUpdateViewCount
CP_END_MAPLETV
