CP_CheckPassword = @0001
CP_WorldInfoRequest = @0002

CP_CheckUserLimit = @0005
CP_SelectWorld = @0009
CP_SelectCharacter =@000A
CP_MigrateIn = @000B
CP_CheckDuplicatedID = @000C
CP_CreateNewCharacter = @0011
CP_DeleteCharacter

CP_AliveAck = @0014
CP_ExceptionLog = @0015

CP_JMS_GetMapLogin = @001E

CP_UserTransferFieldRequest = @0021
CP_UserTransferChannelRequest = @0022
CP_UserMigrateToCashShopRequest = @0023
CP_UserMove = @0024
CP_UserSitRequest = @0025
CP_UserPortableChairSitRequest = @0026

CP_UserMeleeAttack = @002A
CP_UserShootAttack = @002B
CP_UserMagicAttack = @002C

CP_UserChat = @0031

CP_UserSelectNpc = @003A
CP_UserRemoteShopOpenRequest = @003B
CP_UserScriptMessageAnswer = @003C

CP_UserShopRequest = @003E
CP_UserTrunkRequest = @003F

CP_UserSortItemRequest = @0047
CP_UserGatherItemRequest = @0048
CP_UserChangeSlotPositionRequest = @0049
CP_UserStatChangeItemUseRequest = @004A

CP_UserMobSummonItemUseRequest = @004D

CP_UserConsumeCashItemUseRequest = @0051

CP_UserSkillLearnItemUseRequest = @0054

CP_UserPortalScrollUseRequest = @0058
CP_UserUpgradeItemUseRequest = @0059
CP_UserHyperUpgradeItemUseRequest = @005A
CP_UserItemOptionUpgradeItemUseRequest = @005B

CP_UserItemReleaseRequest = @005D
CP_UserAbilityUpRequest = @005E
CP_UserAbilityMassUpRequest = @005F
CP_UserChangeStatRequest = @0060
CP_UserChangeStatRequestByItemOption = @0061
CP_UserSkillUpRequest = @0062
CP_UserSkillUseRequest = @0063
CP_UserSkillCancelRequest = @0064
CP_UserSkillPrepareRequest = @0065
CP_UserDropMoneyRequest = @0066

CP_UserCharacterInfoRequest = @0069

CP_UserPortalScriptRequest = @006D
CP_UserPortalTeleportRequest = @006E


CP_FuncKeyMappedModified = @009B

CP_UserMigrateToITCRequest = @00A5
CP_UserExpUpItemUseRequest = @00A6
CP_UserTempExpUseRequest = @00A7

CP_DropPickUpRequest

CP_BEGIN_CASHSHOP
CP_CashShopChargeParamRequest = @0110
CP_CashShopQueryCashRequest = @0111
CP_CashShopCashItemRequest = @0112
CP_CashShopCheckCouponRequest = @0113

CP_JMS_RECOMMENDED_AVATAR = @0116
CP_END_CASHSHOP


CP_BEGIN_ITC
CP_ITCChargeParamRequest = @012A
CP_ITCQueryCashRequest = @012B
CP_ITCItemRequest = @012C
CP_END_ITC