CP_CheckPassword = @0001
CP_AccountInfoRequest
CP_WorldInfoRequest = @0004
CP_SelectWorld = @0005
CP_CheckUserLimit = @0006
CP_ViewAllChar = @000D
CP_SelectCharacter = @0013
CP_MigrateIn = @0014
CP_CheckDuplicatedID = @0015
CP_CreateNewCharacter = @0016
CP_DeleteCharacter = @0017
CP_AliveAck = @0019
CP_JMS_CheckGameGuardUpdated = @001C
CP_ExceptionLog

CP_UserTransferFieldRequest = @0023
CP_UserTransferChannelRequest = @0024
CP_UserMigrateToCashShopRequest = @0025
CP_UserMove = @0026
CP_UserSitRequest = @0027
CP_UserPortableChairSitRequest = @0028
CP_UserMeleeAttack = @0029
CP_UserShootAttack = @002A
CP_UserMagicAttack = @002B
CP_UserBodyAttack = @002C
CP_UserHit = @002D
CP_UserChat = @002E
CP_UserADBoardClose = @002F

CP_UserSelectNpc = @0036
CP_UserRemoteShopOpenRequest
CP_UserScriptMessageAnswer = @0038
CP_UserShopRequest = @0039
CP_UserTrunkRequest = @003A
CP_UserGatherItemRequest = @0040
CP_UserSortItemRequest = @0041
CP_UserChangeSlotPositionRequest = @0042
CP_UserStatChangeItemUseRequest = @0043


CP_UserMobSummonItemUseRequest = @0046
CP_UserPetFoodItemUseRequest = @0047

CP_UserConsumeCashItemUseRequest = @0049

CP_UserSkillLearnItemUseRequest = @004B

CP_UserPortalScrollUseRequest = @004E
CP_UserUpgradeItemUseRequest = @004F
CP_UserAbilityUpRequest = @0050
CP_UserAbilityMassUpRequest
CP_UserSkillUpRequest = @0052
CP_UserSkillUseRequest = @0053
CP_UserSkillCancelRequest = @0054
CP_UserSkillPrepareRequest = @0055
CP_UserDropMoneyRequest = @0056

CP_UserCharacterInfoRequest = @0059

CP_UserPortalScriptRequest = @005C
CP_UserPortalTeleportRequest = @005D


CP_FuncKeyMappedModified = @007B

CP_DropPickUpRequest = @00AB