CP_CheckPassword = @0001
CP_AccountInfoRequest
CP_WorldInfoRequest = @0004
CP_SelectWorld = @0005
CP_CheckUserLimit = @0006
CP_ViewAllChar = @000D
CP_SelectCharacter = @0013
CP_MigrateIn = @0014
CP_CheckDuplicatedID = @0015
CP_CreateNewCharacter = @0016
CP_JMS_164_KOC_UI_Request = @0017
CP_DeleteCharacter = @0018
CP_AliveAck = @0019
CP_ExceptionLog

CP_UserTransferFieldRequest = @0025
CP_UserTransferChannelRequest = @0026
CP_UserMigrateToCashShopRequest = @0027
#CP_UserMove

CP_UserChat = @0030

CP_UserSelectNpc
CP_UserRemoteShopOpenRequest
CP_UserScriptMessageAnswer
CP_UserShopRequest
CP_UserTrunkRequest

CP_UserChangeSlotPositionRequest
CP_UserStatChangeItemUseRequest

CP_UserConsumeCashItemUseRequest

CP_UserPortalScrollUseRequest
CP_UserUpgradeItemUseRequest

CP_UserAbilityUpRequest
CP_UserAbilityMassUpRequest

CP_UserSkillUpRequest
CP_UserSkillUseRequest
CP_UserSkillCancelRequest
CP_UserSkillPrepareRequest

CP_UserDropMoneyRequest

CP_UserCharacterInfoRequest

CP_UserPortalScriptRequest = @0063
CP_UserPortalTeleportRequest = @0064


CP_FuncKeyMappedModified = @0085

CP_UserMigrateToITCRequest = @009A