LP_BEGIN_SOCKET
LP_CheckPasswordResult = @0000
LP_GuestIDLoginResult = @0001
LP_AccountInfoResult = @0002
LP_CheckUserLimitResult = @0003
LP_SetAccountResult = @0004
LP_ConfirmEULAResult = @0005
LP_CheckPinCodeResult = @0006
LP_UpdatePinCodeResult = @0007
LP_ViewAllCharResult = @0008
LP_SelectCharacterByVACResult = @0009
LP_WorldInformation = @000A
LP_SelectWorldResult = @000B
LP_SelectCharacterResult = @000C
LP_CheckDuplicatedIDResult = @000D
LP_CreateNewCharacterResult = @000E
LP_DeleteCharacterResult = @000F
LP_MigrateCommand = @0010
LP_AliveReq = @0011
LP_AuthenCodeChanged = @0012
LP_AuthenMessage = @0013
LP_SecurityPacket = @0014
LP_EnableSPWResult
LP_DeleteCharacterOTPRequest
#
#
LP_CheckCrcResult = @0019
LP_LatestConnectedWorld = @001A
LP_RecommendWorldMessage = @001B
LP_CheckSPWResult = @001C
LP_END_SOCKET

LP_BEGIN_CHARACTERDATA
LP_InventoryOperation = @001D
LP_InventoryGrow = @001E
LP_StatChanged = @001F
LP_TemporaryStatSet = @0020
LP_TemporaryStatReset = @0021
LP_ForcedStatSet = @0022
LP_ForcedStatReset = @0023
LP_ChangeSkillRecordResult = @0024
LP_SkillUseResult = @0025
LP_GivePopularityResult = @0026
LP_Message = @0027
LP_SendOpenFullClientLink = @0028
LP_MemoResult = @0029
LP_MapTransferResult = @002A
LP_AntiMacroResult = @002B
LP_InitialQuizStart
LP_ClaimResult = @002D
LP_SetClaimSvrAvailableTime = @002E
LP_ClaimSvrStatusChanged = @002F
LP_SetTamingMobInfo = @0030
LP_QuestClear = @0031
LP_EntrustedShopCheckResult = @0032
LP_SkillLearnItemResult = @0033
LP_GatherItemResult = @0034
LP_SortItemResult = @0035
LP_RemoteShopOpenResult = @0036
LP_SueCharacterResult = @0037
LP_MigrateToCashShopResult = @0038
LP_TradeMoneyLimit = @0039
LP_SetGender = @003A
LP_GuildBBS = @003B
LP_PetDeadMessage
LP_CharacterInfo = @003D
LP_PartyResult = @003E
LP_FriendResult = @003F
LP_GuildRequest
LP_GuildResult = @0041
LP_AllianceResult = @0042
LP_TownPortal = @0043
LP_BroadcastMsg = @0044
LP_IncubatorResult = @0045
LP_ShopScannerResult = @0046
LP_ShopLinkResult = @0047
LP_MarriageRequest = @0048
LP_MarriageResult = @0049
LP_WeddingGiftResult = @004A
LP_MarriedPartnerMapTransfer = @004B
LP_CashPetFoodResult = @004C
LP_SetWeekEventMessage = @004D
LP_SetPotionDiscountRate = @004E
LP_BridleMobCatchFail = @004F
LP_ImitatedNPCResult = @0050
LP_ImitatedNPCData = @0051
LP_LimitedNPCDisableInfo = @0052
LP_MonsterBookSetCard = @0053
LP_MonsterBookSetCover = @0054
LP_HourChanged = @0055
LP_MiniMapOnOff = @0056
LP_ConsultAuthkeyUpdate = @0057
LP_ClassCompetitionAuthkeyUpdate = @0058
LP_WebBoardAuthkeyUpdate = @0059
LP_SessionValueUE = @005A
LP_PartyValue = @005B
LP_FieldSetVariable = @005C
LP_BonusExpRateChanged = @005D
LP_FamilyChartResult = @005E
LP_FamilyInfoResult = @005F
LP_FamilyResult = @0060
LP_FamilyJoinRequest = @0061
LP_FamilyJoinRequestResult = @0062
LP_FamilyJoinAccepted = @0063
LP_FamilyPrivilegeList = @0064
LP_FamilyFamousPointIncResult = @0065
LP_FamilyNotifyLoginOrLogout = @0066
LP_FamilySetPrivilege = @0067
LP_FamilySummonRequest = @0068
LP_NotifyLevelUp = @0069
LP_NotifyWedding = @006A
LP_NotifyJobChange = @006B
LP_IncRateChanged
LP_MapleTVUseRes = @006D
LP_AvatarMegaphoneRes = @006E
LP_AvatarMegaphoneUpdateMessage = @006F
LP_AvatarMegaphoneClearMessage = @0070
LP_CancelNameChangeResult = @0071
LP_CancelTransferWorldResult = @0072
LP_DestroyShopResult = @0073
LP_FAKEGMNOTICE = @0074
LP_SuccessInUseGachaponBox = @0075
LP_NewYearCardRes = @0076
LP_RandomMorphRes = @0077
LP_CancelNameChangeByOther = @0078
LP_SetBuyEquipExt = @0079
LP_ScriptProgressMessage = @007A
LP_DataCRCCheckFailed = @007B
LP_MacroSysDataInit = @007C
LP_END_CHARACTERDATA

LP_BEGIN_STAGE
LP_SetField = @007D
LP_SetITC = @007E
LP_SetCashShop = @007F
LP_END_STAGE

LP_BEGIN_MAP
LP_SetBackgroundEffect = @0080
LP_SetMapObjectVisible = @0081
LP_ClearBackgroundEffect = @0082
LP_END_MAP

LP_BEGIN_FIELD
LP_TransferFieldReqIgnored = @0083
LP_TransferChannelReqIgnored = @0084
LP_FieldSpecificData  = @0085
LP_GroupMessage = @0086
LP_Whisper = @0087
LP_CoupleMessage = @0088
LP_MobSummonItemUseResult = @0089
LP_FieldEffect = @008A
LP_FieldObstacleOnOff = @008B
LP_FieldObstacleOnOffStatus = @008C
LP_FieldObstacleAllReset = @008D
LP_BlowWeather = @008E
LP_PlayJukeBox = @008F
LP_AdminResult = @0090
LP_Quiz = @0091
LP_Desc = @0092
LP_Clock = @0093
LP_CONTIMOVE = @0094
LP_CONTISTATE = @0095
###
LP_SetQuestClear = @0096
LP_SetQuestTime = @0097
LP_Warn = @0098
LP_SetObjectState = @0099
LP_DestroyClock = @009A
LP_ShowArenaResult = @009B
###
LP_StalkResult
LP_MassacreIncGauge = @009D
###
LP_MassacreResult = @009E
###
LP_QuickslotMappedInit = @009F
LP_BEGIN_USERPOOL
LP_UserEnterField = @00A0
LP_UserLeaveField = @00A1
LP_BEGIN_USERCOMMON
LP_UserChat = @00A2
LP_UserChatNLCPQ = @00A3
LP_UserADBoard = @00A4
LP_UserMiniRoomBalloon = @00A5
LP_UserConsumeItemEffect = @00A6
LP_UserItemUpgradeEffect = @00A7
LP_BEGIN_PET
LP_PetActivated = @00A8
LP_PetEvol
LP_PetMove = @00AA
LP_PetAction = @00AB
LP_PetNameChanged = @00AC
LP_PetLoadExceptionList = @00AD
LP_PetActionCommand = @00AE
LP_END_PET
LP_BEGIN_SUMMONED
LP_SummonedEnterField = @00AF
LP_SummonedLeaveField = @00B0
LP_SummonedMove = @00B1
LP_SummonedAttack = @00B2
LP_SummonedSkill = @00B3
LP_SummonedHit = @00B4
LP_END_SUMMONED
LP_BEGIN_DRAGON
LP_DragonEnterField = @00B5
LP_DragonMove = @00B6
LP_DragonLeaveField
LP_END_DRAGON
LP_END_USERCOMMON
LP_BEGIN_USERREMOTE
LP_UserMove = @00B9
LP_UserMeleeAttack = @00BA
LP_UserShootAttack = @00BB
LP_UserMagicAttack = @00BC
LP_UserBodyAttack = @00BD
LP_UserSkillPrepare = @00BE
LP_UserSkillCancel = @00BF
LP_UserHit = @00C0
LP_UserEmotion = @00C1
LP_UserSetActiveEffectItem = @00C2
LP_UserShowUpgradeTombEffect
LP_UserSetActivePortableChair = @00C4
LP_UserAvatarModified = @00C5
LP_UserEffectRemote = @00C6
LP_UserTemporaryStatSet = @00C7
LP_UserTemporaryStatReset = @00C8
LP_UserHP = @00C9
LP_UserGuildNameChanged = @00CA
LP_UserGuildMarkChanged = @00CB
LP_UserThrowGrenade = @00CC
LP_END_USERREMOTE
LP_BEGIN_USERLOCAL
LP_UserSitResult = @00CD
LP_UserEffectLocal = @00CE
LP_UserTeleport = @00CF
LP_Premium
LP_MesoGive_Succeeded = @00D0
LP_MesoGive_Failed = @00D1
LP_Random_Mesobag_Succeed = @00D2
LP_Random_Mesobag_Failed = @00D3
LP_UserQuestResult
LP_NotifyHPDecByField
LP_UserPetSkillChanged
LP_UserBalloonMsg = @00D6
LP_PlayEventSound
LP_PlayMinigameSound
LP_UserMakerResult = @00D9
LP_UserOpenConsultBoard
LP_UserOpenClassCompetitionPage = @00DB
LP_UserOpenUI = @00DC
LP_SetDirectionMode = @00DD
LP_SetStandAloneMode = @00DE
LP_UserHireTutor = @00DF
LP_UserTutorMsg = @00E0
LP_IncCombo = @00E1
LP_UserRandomEmotion
LP_ResignQuestReturn
LP_PassMateName
LP_SetRadioSchedule
LP_UserOpenSkillGuide
LP_UserNoticeMsg
LP_UserChatMsg
LP_UserBuffzoneEffect
LP_UserDamageMeter
LP_UserTimeBombAttack
LP_UserPassiveMove
LP_UserFollowCharacterFailed
LP_JMS_Poll_Question
LP_SkillCooltimeSet = @00EA
LP_END_USERLOCAL
LP_END_USERPOOL
LP_BEGIN_MOBPOOL
LP_MobEnterField = @00EC
LP_MobLeaveField = @00ED
LP_MobChangeController = @00EE
LP_BEGIN_MOB
LP_MobMove = @00EF
LP_MobCtrlAck = @00F0
LP_MobCtrlHint
LP_MobStatSet = @00F2
LP_MobStatReset = @00F3
LP_MobSuspendResetON = @00F4
LP_MobAffected
LP_MobDamaged = @00F6
LP_MobSpecialEffectBySkill
LP_MobHPChange
LP_MobCrcKeyChanged
LP_MobHPIndicator = @00FA
LP_MobCatchEffect = @00FB
LP_MobEffectByItem = @00FC
LP_MobSpeaking
LP_MobChargeCount
LP_MobSkillDelay
LP_MobNextAttack
LP_MobAttackedByMob
LP_END_MOB
LP_END_MOBPOOL
LP_BEGIN_NPCPOOL
#LP_ImitatedNPCData
#LP_LimitedNPCDisableInfo
LP_NpcEnterField = @0101
LP_NpcLeaveField = @0102
LP_NpcChangeController = @0103
LP_BEGIN_NPC
LP_NpcMove = @0104
LP_NpcUpdateLimitedInfo
LP_NpcSpecialAction
LP_END_NPC
LP_BEGIN_NPCTEMPLATE
LP_NpcSetScript = @0107
LP_END_NPCTEMPLATE
LP_END_NPCPOOL
LP_BEGIN_EMPLOYEEPOOL
LP_EmployeeEnterField = @0109
LP_EmployeeLeaveField = @010A
LP_EmployeeMiniRoomBalloon = @010B
LP_END_EMPLOYEEPOOL
LP_BEGIN_DROPPOOL
LP_DropEnterField = @010C
LP_DropLeaveField = @010D
LP_END_DROPPOOL
LP_BEGIN_MESSAGEBOXPOOL
LP_CreateMessgaeBoxFailed = @010E
LP_MessageBoxEnterField = @010F
LP_MessageBoxLeaveField = @0110
LP_END_MESSAGEBOXPOOL
LP_BEGIN_AFFECTEDAREAPOOL
LP_AffectedAreaCreated = @0111
LP_AffectedAreaRemoved = @0112
LP_END_AFFECTEDAREAPOOL
LP_BEGIN_TOWNPORTALPOOL
LP_TownPortalCreated = @0113
LP_TownPortalRemoved = @0114
LP_END_TOWNPORTALPOOL
LP_BEGIN_REACTORPOOL
LP_ReactorChangeState = @0115
LP_ReactorMove
LP_ReactorEnterField = @0117
LP_ReactorLeaveField = @0118
LP_END_REACTORPOOL
LP_BEGIN_ETCFIELDOBJ
LP_SnowBallState = @0119
LP_SnowBallHit = @011A
LP_SnowBallMsg = @011B
LP_SnowBallTouch = @011C
###
LP_CoconutHit = @011D
LP_CoconutScore = @011E
###
LP_HealerMove = @011F
LP_PulleyStateChange = @0120
###
LP_MCarnivalEnter = @0121
LP_MCarnivalPersonalCP = @0122
LP_MCarnivalTeamCP = @0123
LP_MCarnivalResultSuccess = @0124
LP_MCarnivalResultFail = @0125
LP_MCarnivalDeath = @0126
LP_MCarnivalMemberOut = @0127
LP_MCarnivalGameResult
###
LP_ArenaScore = @0129
###
LP_BattlefieldEnter
LP_BattlefieldScore
LP_BattlefieldTeamChanged
###
LP_WitchtowerScore = @012D
###
LP_HontaleTimer = @012E
###
LP_ZakumTimer = @012F
LP_END_ETCFIELDOBJ
LP_BEGIN_SCRIPT
LP_ScriptMessage = @0130
LP_END_SCRIPT
LP_BEGIN_SHOP
LP_OpenShopDlg = @0131
LP_ShopResult = @0132
LP_END_SHOP
LP_BEGIN_ADMINSHOP
LP_AdminShopResult = @0133
LP_AdminShopCommodity = @0134
LP_END_ADMINSHOP
LP_TrunkResult = @0135
LP_BEGIN_STOREBANK
LP_StoreBankGetAllResult = @0136
LP_StoreBankResult = @0137
LP_END_STOREBANK
LP_RPSGame = @0138
LP_Messenger = @0139
LP_MiniRoom = @013A
LP_BEGIN_TOURNAMENT
LP_Tournament = @013B
LP_TournamentMatchTable = @013C
LP_TournamentSetPrize = @013D
LP_TournamentNoticeUEW = @013E
LP_TournamentAvatarInfo = @013F
LP_END_TOURNAMENT
LP_BEGIN_WEDDING
LP_WeddingProgress = @013F
LP_WeddingCremonyEnd = @0141
LP_END_WEDDING
LP_Parcel = @0142
LP_END_FIELD

LP_BEGIN_CASHSHOP
LP_CashShopChargeParamResult = @0143
LP_CashShopQueryCashResult = @0144
LP_CashShopCashItemResult = @0145
LP_CashShopPurchaseExpChanged = @0146
LP_CashShopGiftMateInfoResult = @0147
LP_CashShopCheckDuplicatedIDResult = @0148
LP_CashShopCheckNameChangePossibleResult = @0149
LP_CashShopRegisterNewCharacterResult = @014A
LP_CashShopCheckTransferWorldPossibleResult = @014B
LP_CashShopGachaponStampItemResult = @014C
LP_CashShopCashItemGachaponResult = @014D
LP_CashShopCashGachaponOpenResult = @014E
LP_END_CASHSHOP

LP_BEGIN_FUNCKEYMAPPED
LP_FuncKeyMappedInit = @014F
LP_PetConsumeItemInit = @0150
LP_PetConsumeMPItemInit = @0151
LP_END_FUNCKEYMAPPED

LP_BEGIN_MAPLETV
LP_MapleTVUpdateMessage = @0155
LP_MapleTVClearMessage = @0156
LP_MapleTVSendMessageResult = @0157
LP_BroadSetFlashChangeEvent
LP_END_MAPLETV

LP_BEGIN_ITC
LP_ITCChargeParamResult = @015B
LP_ITCQueryCashResult = @015C
LP_ITCNormalItemResult
LP_END_ITC

LP_BEGIN_ITEMUPGRADE
LP_ItemUpgrade_s
LP_ItemUpgradeResult = @0162
LP_ItemUpgradeFail
LP_ItemUpgrade_e
LP_END_ITEMUPGRADE

LP_BEGIN_VEGA
LP_Vega_s
LP_VegaResult = @0166
LP_VegaFail
LP_Vega_e
LP_END_VEGA

LP_LogoutGift
LP_NO
