CP_BEGIN_SOCKET
CP_CheckPassword = @0001
CP_GuestIDLogin = @0002
CP_AccountInfoRequest
CP_WorldInfoRequest = @0004
CP_SelectWorld = @0005
CP_CheckUserLimit = @0006
CP_ConfirmEULA = @0007
CP_SetGender = @0008
CP_CheckPinCode = @0009
CP_UpdatePinCode = @000A
CP_WorldRequest = @000B
CP_LogoutWorld = @000C
CP_ViewAllChar = @000D
CP_SelectCharacterByVAC = @000E
CP_VACFlagSet
CP_CheckNameChangePossible = @0010
CP_RegisterNewCharacter
CP_CheckTransferWorldPossible = @0012
CP_SelectCharacter = @0013
CP_MigrateIn = @0014
CP_CheckDuplicatedID = @0015
CP_CreateNewCharacter = @0016
CP_CreateNewCharacterInCS
CP_DeleteCharacter = @0017
CP_AliveAck = @0018
CP_ExceptionLog = @0019
CP_SecurityPacket = @001A
#STRANGE_DATA = @001B
#RELOG = @001C
CP_EnableSPWRequest = @001D
CP_CheckSPWRequest = @001E
CP_EnableSPWRequestByACV = @001F
CP_CheckSPWRequestByACV = @0020
CP_CheckOTPRequest
CP_CheckDeleteCharacterOTP
CP_CreateSecurityHandle
CP_SSOErrorLog
CP_ClientDumpLog
CP_CheckExtraCharInfo
CP_CreateNewCharacter_Ex
CP_END_SOCKET
CP_BEGIN_USER
CP_UserTransferFieldRequest = @0026
CP_UserTransferChannelRequest = @0027
CP_UserMigrateToCashShopRequest = @0028
CP_UserMove = @0029
CP_UserSitRequest = @002A
CP_UserPortableChairSitRequest = @002B
CP_UserMeleeAttack = @002C
CP_UserShootAttack = @002D
CP_UserMagicAttack = @002E
CP_UserBodyAttack = @002F
CP_UserHit = @0030
CP_UserChat = @0031
CP_UserADBoardClose = @0032
CP_UserEmotion = @0033
CP_UserActivateEffectItem = @0034
CP_UserUpgradeTombEffect = @0035
CP_UserHP
CP_Premium
CP_UserBanMapByMob = @0038
CP_UserMonsterBookSetCover = @0039
CP_UserSelectNpc = @003A
CP_UserRemoteShopOpenRequest = @003B
CP_UserScriptMessageAnswer = @003C
CP_UserShopRequest = @003D
CP_UserTrunkRequest = @003E
CP_UserEntrustedShopRequest = @003F
CP_UserStoreBankRequest = @0040
CP_UserParcelRequest = @0041
CP_ShopScannerRequest = @0042
CP_ShopLinkRequest = @0043
CP_AdminShopRequest = @0044
CP_UserGatherItemRequest = @0045
CP_UserSortItemRequest = @0046
CP_UserChangeSlotPositionRequest = @0047
CP_UserStatChangeItemUseRequest = @0048
CP_UserStatChangeItemCancelRequest = @0049
CP_UserStatChangeByPortableChairRequest
CP_UserMobSummonItemUseRequest = @004B
CP_UserPetFoodItemUseRequest = @004C
CP_UserTamingMobFoodItemUseRequest = @004D
CP_UserScriptItemUseRequest = @004E
CP_UserConsumeCashItemUseRequest = @004F
CP_UserDestroyPetItemRequest
CP_UserBridleItemUseRequest = @0051
CP_UserSkillLearnItemUseRequest = @0052
CP_UserShopScannerItemUseRequest
CP_UserMapTransferItemUseRequest = @0054
CP_UserPortalScrollUseRequest = @0055
CP_UserUpgradeItemUseRequest = @0056
CP_UserAbilityUpRequest = @0057
CP_UserAbilityMassUpRequest = @0058
CP_UserChangeStatRequest = @0059
CP_UserSkillUpRequest = @005A
CP_UserSkillUseRequest = @005B
CP_UserSkillCancelRequest = @005C
CP_UserSkillPrepareRequest = @005D
CP_UserDropMoneyRequest = @005E
CP_UserGivePopularityRequest = @005F
CP_UserPartyRequest
CP_UserCharacterInfoRequest = @0061
CP_UserActivatePetRequest = @0062
CP_UserTemporaryStatUpdateRequest = @0063
CP_UserPortalScriptRequest = @0064
CP_UserPortalTeleportRequest = @0065
CP_UserMapTransferRequest = @0066
CP_UserAntiMacroItemUseRequest
CP_UserAntiMacroSkillUseRequest
CP_UserAntiMacroQuestionResult
CP_UserClaimRequest = @006A
CP_UserQuestRequest = @006B
CP_UserCalcDamageStatSetRequest
CP_UserThrowGrenade = @006D
CP_UserMacroSysDataModified = @006E
CP_UserSelectNpcItemUseRequest
CP_UserLotteryItemUseRequest = @0070
CP_UserItemMakeRequest = @0071
CP_UserSueCharacterRequest
CP_UserUseGachaponBoxRequest
CP_UserUseGachaponRemoteRequest = @0074
CP_UserUseWaterOfLife = @0075
CP_BroadcastMsg = @0076
CP_GroupMessage = @0077
CP_Whisper = @0078
CP_CoupleMessage = @0079
CP_Messenger = @007A
CP_MiniRoom = @007B
CP_PartyRequest = @007C
CP_PartyResult = @007D
CP_GuildRequest = @007E
CP_GuildResult = @007F
CP_Admin = @0080
CP_Log = @0081
CP_FriendRequest = @0082
CP_MemoRequest = @0083
CP_MemoFlagRequest
CP_EnterTownPortalRequest = @0085
CP_EnterOpenGateRequest
CP_SlideRequest
CP_FuncKeyMappedModified = @0087
CP_RPSGame = @0089
CP_MarriageRequest = @008A
CP_WeddingWishListRequest = @008B
CP_WeddingProgress
CP_GuestBless
CP_BoobyTrapAlert
CP_StalkBegin
CP_AllianceRequest = @008F
CP_AllianceResult = @0090
CP_FamilyChartRequest = @0091
CP_FamilyInfoRequest = @0092
CP_FamilyRegisterJunior = @0093
CP_FamilyUnregisterJunior = @0094
CP_FamilyUnregisterParent = @0095
CP_FamilyJoinResult = @0096
CP_FamilyUsePrivilege = @0097
CP_FamilySetPrecept = @0098
CP_FamilySummonResult = @0099
CP_ChatBlockUserReq
CP_GuildBBS = @009B
CP_UserMigrateToITCRequest = @009C
CP_UserExpUpItemUseRequest = @009D
CP_UserTempExpUseRequest = @009E
CP_NewYearCardRequest = @009F
CP_RandomMorphRequest
CP_CashItemGachaponRequest = @00A1
CP_CashGachaponOpenRequest
CP_ChangeMaplePointRequest
CP_TalkToTutor = @00A2
CP_RequestIncCombo = @00A3
CP_MobCrcKeyChangedReply
CP_RequestSessionValue
CP_UpdateGMBoard
CP_AccountMoreInfo
CP_FindFriend
CP_AcceptAPSPEvent
CP_UserDragonBallBoxRequest
CP_UserDragonBallSummonRequest
CP_BEGIN_PET
CP_PetMove = @00A7
CP_PetAction = @00A8
CP_PetInteractionRequest = @00A9
CP_PetDropPickUpRequest = @00AA
CP_PetStatChangeItemUseRequest = @00AB
CP_PetUpdateExceptionListRequest = @00AC
CP_END_PET
CP_BEGIN_SUMMONED
CP_SummonedMove = @00AF
CP_SummonedAttack = @00B0
CP_SummonedHit = @00B1
CP_SummonedSkill = @00B2
CP_Remove
CP_END_SUMMONED
CP_BEGIN_DRAGON
CP_DragonMove
CP_END_DRAGON
CP_QuickslotKeyMappedModified = @00B7
CP_PassiveskillInfoUpdate
CP_UpdateScreenSetting
CP_UserAttackUser_Specific
CP_UserPamsSongUseRequest
CP_QuestGuideRequest
CP_UserRepeatEffectRemove
CP_END_USER
CP_BEGIN_FIELD
CP_BEGIN_LIFEPOOL
CP_BEGIN_MOB
CP_MobMove = @00BC
CP_MobApplyCtrl = @00BD
CP_MobDropPickUpRequest
CP_MobHitByObstacle = @00BF
CP_MobHitByMob = @00C0
CP_MobSelfDestruct = @00C1
CP_MobAttackMob = @00C2
CP_MobSkillDelayEnd
CP_MobTimeBombEnd
CP_MobEscortCollision
CP_MobRequestEscortInfo
CP_MobEscortStopEndRequest
CP_END_MOB
CP_BEGIN_NPC
CP_NpcMove = @00C5
CP_NpcSpecialAction
CP_END_NPC
CP_END_LIFEPOOL
CP_BEGIN_DROPPOOL
CP_DropPickUpRequest = @00CA
CP_END_DROPPOOL
CP_BEGIN_REACTORPOOL
CP_ReactorHit = @00CD
CP_ReactorTouch = @00CE
CP_RequireFieldObstacleStatus = @00CF
CP_END_REACTORPOOL
CP_BEGIN_EVENT_FIELD
CP_EventStart
CP_SnowBallHit = @00D3
CP_SnowBallTouch = @00D4
CP_CoconutHit = @00D5
CP_TournamentMatchTable = @00D6
CP_PulleyHit
CP_END_EVENT_FIELD
CP_BEGIN_MONSTER_CARNIVAL_FIELD
CP_MCarnivalRequest = @00DA
CP_END_MONSTER_CARNIVAL_FIELD
CP_CONTISTATE = @00DC
CP_BEGIN_PARTY_MATCH
CP_INVITE_PARTY_MATCH = @00DD
CP_CANCEL_INVITE_PARTY_MATCH = @00DF
CP_END_PARTY_MATCH
CP_RequestFootHoldInfo
CP_FootHoldInfo
CP_END_FIELD
CP_BEGIN_CASHSHOP
CP_CashShopChargeParamRequest = @00E4
CP_CashShopQueryCashRequest = @00E5
CP_CashShopCashItemRequest
CP_CashShopCheckCouponRequest = @00E6
CP_CashShopGiftMateInfoRequest
CP_END_CASHSHOP
CP_CheckSSN2OnCreateNewCharacter
CP_CheckSPWOnCreateNewCharacter
CP_FirstSSNOnCreateNewCharacter
CP_BEGIN_RAISE
CP_RaiseRefesh
CP_RaiseUIState
CP_RaiseIncExp
CP_RaiseAddPiece
CP_END_RAISE
CP_SendMateMail
CP_RequestGuildBoardAuthKey
CP_RequestConsultAuthKey
CP_RequestClassCompetitionAuthKey
CP_RequestWebBoardAuthKey
CP_BEGIN_ITEMUPGRADE
CP_GoldHammerRequest
CP_GoldHammerComplete
CP_ItemUpgradeComplete
CP_END_ITEMUPGRADE
CP_BEGIN_BATTLERECORD
CP_BATTLERECORD_ONOFF_REQUEST
CP_END_BATTLERECORD
CP_BEGIN_MAPLETV
CP_MapleTVSendMessageRequest
CP_MapleTVUpdateViewCount
CP_END_MAPLETV
CP_BEGIN_ITC
CP_ITCChargeParamRequest = @00FD
CP_ITCQueryCashRequest
CP_ITCItemRequest
CP_END_ITC
CP_BEGIN_CHARACTERSALE
CP_CheckDuplicatedIDInCS
CP_END_CHARACTERSALE
CP_LogoutGiftSelect
CP_NO