CP_BEGIN_SOCKET
CP_CheckPassword = @0001
CP_AccountInfoRequest
CP_WorldInfoRequest = @0003
CP_SelectWorld = @0004
CP_LogoutWorld
CP_SelectCharacter = @0005
CP_MigrateIn = @0006
CP_CheckDuplicatedID = @0007
CP_CreateNewCharacter = @0008
CP_DeleteCharacter = @0009
CP_AliveAck = @000A
CP_ExceptionLog = @000B
CP_SecurityPacket
CP_CheckUserLimit = @0011
CP_END_SOCKET
CP_BEGIN_USER
CP_UserTransferFieldRequest
CP_UserTransferChannelRequest
CP_UserMigrateToCashShopRequest
CP_UserMove
CP_UserSitRequest
CP_UserPortableChairSitRequest
CP_UserMeleeAttack
CP_UserShootAttack
CP_UserMagicAttack
CP_UserBodyAttack
CP_UserHit
CP_UserChat
CP_UserADBoardClose
CP_UserActivateEffectItem
CP_UserMonsterBookSetCover
CP_UserSelectNpc
CP_UserRemoteShopOpenRequest
CP_UserScriptMessageAnswer
CP_UserShopRequest
CP_UserTrunkRequest
CP_UserEntrustedShopRequest
CP_ShopScannerRequest
CP_UserGatherItemRequest
CP_UserSortItemRequest
CP_UserChangeSlotPositionRequest
CP_UserStatChangeItemUseRequest
CP_UserStatChangeItemCancelRequest
CP_UserMobSummonItemUseRequest
CP_UserPetFoodItemUseRequest
CP_UserConsumeCashItemUseRequest
CP_UserBridleItemUseRequest
CP_UserSkillLearnItemUseRequest
CP_UserShopScannerItemUseRequest
CP_UserMapTransferItemUseRequest
CP_UserPortalScrollUseRequest
CP_UserUpgradeItemUseRequest
CP_UserAbilityUpRequest
CP_UserChangeStatRequest
CP_UserSkillUpRequest
CP_UserSkillUseRequest
CP_UserSkillCancelRequest
CP_UserSkillPrepareRequest
CP_UserDropMoneyRequest
CP_UserGivePopularityRequest
CP_UserCharacterInfoRequest
CP_UserActivatePetRequest
CP_UserTemporaryStatUpdateRequest
CP_UserPortalScriptRequest
CP_UserPortalTeleportRequest
CP_UserMapTransferRequest
CP_UserQuestRequest
CP_UserExpUpItemUseRequest
CP_UserTempExpUseRequest
CP_GroupMessage
CP_Whisper
CP_Messenger
CP_MiniRoom
CP_PartyRequest
CP_Admin
CP_Log
CP_FriendRequest
CP_FuncKeyMappedModified
CP_RPSGame
CP_MarriageRequest
CP_UserMigrateToITCRequest
CP_END_USER
CP_BEGIN_PET
CP_PetMove
CP_PetAction
CP_PetInteractionRequest
CP_PetDropPickUpRequest
CP_PetStatChangeItemUseRequest
CP_PetUpdateExceptionListRequest
CP_END_PET
CP_BEGIN_SUMMONED
CP_SummonedMove
CP_SummonedAttack
CP_SummonedHit
CP_SummonedSkill
CP_Remove
CP_END_SUMMONED
CP_BEGIN_FIELD
CP_BEGIN_LIFEPOOL
CP_BEGIN_MOB
CP_MobMove
CP_MobApplyCtrl
CP_MobDropPickUpRequest
CP_MobHitByObstacle
CP_MobHitByMob
CP_MobSelfDestruct
CP_END_MOB
CP_BEGIN_NPC
CP_NpcMove
CP_NpcSpecialAction
CP_END_NPC
CP_END_LIFEPOOL
CP_BEGIN_DROPPOOL
CP_DropPickUpRequest
CP_END_DROPPOOL
CP_BEGIN_REACTORPOOL
CP_ReactorHit
CP_ReactorTouch
CP_RequireFieldObstacleStatus
CP_END_REACTORPOOL
CP_BEGIN_EVENT_FIELD
CP_EventStart
CP_SnowBallHit
CP_SnowBallTouch
CP_CoconutHit
CP_TournamentMatchTable
CP_PulleyHit
CP_END_EVENT_FIELD
CP_CONTISTATE
CP_BEGIN_PARTY_MATCH
CP_INVITE_PARTY_MATCH
CP_CANCEL_INVITE_PARTY_MATCH
CP_END_PARTY_MATCH
CP_END_FIELD
CP_BEGIN_CASHSHOP
CP_CashShopChargeParamRequest
CP_CashShopQueryCashRequest
CP_CashShopCashItemRequest
CP_CashShopCheckCouponRequest
CP_CashShopGiftMateInfoRequest
CP_END_CASHSHOP
CP_BEGIN_ITC
CP_ITCChargeParamRequest
CP_ITCQueryCashRequest
CP_ITCItemRequest
CP_END_ITC
CP_BEGIN_MAPLETV
CP_MapleTVSendMessageRequest
CP_MapleTVUpdateViewCount
CP_END_MAPLETV
