LP_BEGIN_SOCKET
LP_CheckPasswordResult = @0001

LP_WorldInformation = @0003
LP_SelectWorldResult = @0004
LP_SelectCharacterResult = @0005
LP_CheckDuplicatedIDResult = @0006
LP_CreateNewCharacterResult = @0007
LP_DeleteCharacterResult = @0008
LP_MigrateCommand = @0009
LP_AliveReq = @000A
LP_AuthenCodeChanged = @000B
LP_AuthenMessage = @000C
LP_JMS_CheckGameGuardUpdatedResult = @000D

LP_SecurityPacket
# [reserved]
# [reserved]
# [reserved]
LP_CheckUserLimitResult = @0014
LP_END_SOCKET
LP_BEGIN_CHARACTERDATA
LP_InventoryOperation = @0018
LP_InventoryGrow = @0019
LP_StatChanged = @001A
LP_TemporaryStatSet
LP_TemporaryStatReset
LP_ForcedStatSet
LP_ForcedStatReset
LP_ChangeSkillRecordResult
LP_SkillUseResult
LP_GivePopularityResult
LP_Message
LP_MemoResult
LP_MapTransferResult
LP_AntiMacroResult
# [reserved]
LP_ClaimResult
LP_SetClaimSvrAvailableTime
LP_ClaimSvrStatusChanged
LP_SetTamingMobInfo
LP_QuestClear
LP_EntrustedShopCheckResult
LP_SkillLearnItemResult
LP_GatherItemResult
LP_SortItemResult
# [reserved]
# [reserved]
LP_CharacterInfo
LP_PartyResult
LP_FriendResult
# [reserved]
LP_GuildResult
LP_AllianceResult
LP_TownPortal
LP_BroadcastMsg
LP_IncubatorResult
LP_ShopScannerResult
LP_ShopLinkResult
LP_MarriageRequest
LP_MarriageResult
LP_WeddingGiftResult
LP_MarriedPartnerMapTransfer
LP_CashPetFoodResult
LP_SetWeekEventMessage
LP_SetPotionDiscountRate
LP_BridleMobCatchFail
# [reserved]
LP_ImitatedNPCResult = @003A
LP_ImitatedNPCData = @003B
LP_MonsterBookSetCard
LP_MonsterBookSetCover
LP_MacroSysDataInit
LP_END_CHARACTERDATA
LP_BEGIN_STAGE
LP_SetField = @0047
LP_SetCashShop = @0048
LP_END_STAGE
LP_BEGIN_MAP
LP_SetBackgroundEffect
LP_ClearBackgroundEffect
LP_END_MAP
LP_BEGIN_FIELD
LP_TransferFieldReqIgnored = @004B
LP_TransferChannelReqIgnored = @004C
LP_FieldSpecificData
LP_GroupMessage
LP_Whisper
LP_MobSummonItemUseResult
LP_FieldEffect
LP_BlowWeather
LP_PlayJukeBox
LP_AdminResult
LP_Quiz
LP_Desc
LP_Clock
LP_CONTIMOVE
LP_CONTISTATE
LP_SetQuestClear
LP_SetQuestTime
LP_SetObjectState
LP_DestroyClock
LP_ShowArenaResult
LP_StalkResult
LP_BEGIN_USERPOOL
LP_UserEnterField = @0060
LP_UserLeaveField = @0061
LP_BEGIN_USERCOMMON
LP_UserChat = @0063
LP_UserADBoard
LP_UserMiniRoomBalloon
LP_UserConsumeItemEffect
LP_UserItemUpgradeEffect
LP_BEGIN_PET
LP_PetActivated = @006A
LP_PetTransferField = @006B
LP_PetMove = @006C
LP_PetAction = @006D
LP_PetNameChanged = @006E
LP_PetActionCommand = @006F
LP_END_PET
LP_BEGIN_SUMMONED
LP_SummonedEnterField = @0072
LP_SummonedLeaveField = @0073
LP_SummonedMove = @0074
LP_SummonedAttack = @0075
LP_SummonedSkill = @0076
LP_SummonedHit = @0077
LP_END_SUMMONED
LP_BEGIN_USERREMOTE
LP_UserMove
LP_UserMeleeAttack
LP_UserShootAttack
LP_UserMagicAttack
LP_UserBodyAttack
LP_UserSkillPrepare
LP_UserSkillCancel
LP_UserHit
LP_UserEmotion
LP_UserSetActiveEffectItem
LP_UserSetActivePortableChair
LP_UserAvatarModified
LP_UserEffectRemote
LP_UserTemporaryStatSet
LP_UserTemporaryStatReset
LP_UserHP
LP_UserGuildNameChanged
LP_UserGuildMarkChanged
LP_UserThrowGrenade
LP_END_USERREMOTE
LP_BEGIN_USERLOCAL
LP_UserSitResult
LP_UserEffectLocal
LP_UserTeleport
LP_Premium
LP_MesoGive_Succeeded
LP_MesoGive_Failed
LP_UserQuestResult
LP_NotifyHPDecByField
LP_UserPetSkillChanged
LP_UserBalloonMsg
LP_PlayEventSound
LP_PlayMinigameSound
LP_SkillCooltimeSet
LP_END_USERLOCAL
LP_END_USERPOOL
LP_BEGIN_MOBPOOL
LP_MobEnterField
LP_MobLeaveField
LP_MobChangeController
LP_BEGIN_MOB
LP_MobMove
LP_MobCtrlAck
LP_MobCtrlHint
LP_MobStatSet
LP_MobStatReset
LP_MobSuspendReset
LP_MobAffected
LP_MobDamaged
LP_MobSpecialEffectBySkill
# [reserved]
LP_MobHPIndicator
LP_MobCatchEffect
LP_MobEffectByItem
LP_MobAttackedByMob
LP_END_MOB
LP_END_MOBPOOL
LP_BEGIN_NPCPOOL
LP_NpcEnterField = @00B1
LP_NpcLeaveField = @00B2
LP_NpcChangeController = @00B3
LP_BEGIN_NPC
LP_NpcMove = @00B5
LP_NpcSpecialAction = @00B6
#
#
LP_END_NPC
LP_BEGIN_NPCTEMPLATE
LP_NpcSetScript = @00BB
LP_END_NPCTEMPLATE
LP_END_NPCPOOL
LP_BEGIN_EMPLOYEEPOOL
LP_EmployeeEnterField = @00BF
LP_EmployeeLeaveField = @00C0
LP_EmployeeMiniRoomBalloon = @00C1
LP_END_EMPLOYEEPOOL
LP_BEGIN_DROPPOOL
LP_DropEnterField = @00C4
LP_DropLeaveField = @00C5
LP_END_DROPPOOL
LP_BEGIN_MESSAGEBOXPOOL
LP_CreateMessgaeBoxFailed = @00C8
LP_MessageBoxEnterField = @00C9
LP_MessageBoxLeaveField = @00CA
LP_END_MESSAGEBOXPOOL
LP_BEGIN_AFFECTEDAREAPOOL
LP_AffectedAreaCreated = @00CD
LP_AffectedAreaRemoved = @00CE
LP_END_AFFECTEDAREAPOOL
LP_BEGIN_TOWNPORTALPOOL
LP_TownPortalCreated = @00D1
LP_TownPortalRemoved = @00D2
LP_END_TOWNPORTALPOOL
LP_BEGIN_REACTORPOOL
LP_ReactorChangeState = @00D5
LP_ReactorMove
LP_ReactorEnterField = @00D7
LP_ReactorLeaveField = @00D8
LP_END_REACTORPOOL
LP_BEGIN_ETCFIELDOBJ
LP_SnowBallState
LP_SnowBallHit
LP_SnowBallMsg
LP_SnowBallTouch
LP_CoconutHit
LP_CoconutScore
LP_HealerMove
LP_PulleyStateChange
LP_MCarnivalEnter
LP_MCarnivalPersonalCP
LP_MCarnivalTeamCP
LP_MCarnivalResultSuccess
LP_MCarnivalResultFail
LP_MCarnivalDeath
LP_MCarnivalMemberOut
LP_MCarnivalGameResult
LP_ArenaScore
LP_ZakumTimer
LP_END_ETCFIELDOBJ
LP_BEGIN_SCRIPT
LP_ScriptMessage = @00ED
LP_END_SCRIPT
LP_BEGIN_SHOP
LP_OpenShopDlg = @00F0
LP_ShopResult = @00F1
LP_END_SHOP
LP_TrunkResult = @00F3
LP_BEGIN_STOREBANK
LP_StoreBankGetAllResult = @00F5
LP_StoreBankResult = @00F6
LP_END_STOREBANK
LP_RPSGame = @00F8
LP_Messenger = @00F9
LP_MiniRoom = @00FA
LP_BEGIN_TOURNAMENT
LP_Tournament
LP_TournamentMatchTable
LP_TournamentSetPrize
LP_TournamentNoticeUEW
LP_TournamentAvatarInfo
LP_END_TOURNAMENT
LP_BEGIN_WEDDING
LP_WeddingProgress
LP_WeddingCremonyEnd
LP_END_WEDDING
LP_BEGIN_JMS_PACHINKO
LP_END_JMS_PACHINKO
LP_Parcel = @0102
LP_END_FIELD
LP_BEGIN_CASHSHOP
LP_CashShopChargeParamResult
LP_CashShopQueryCashResult
LP_CashShopCashItemResult
LP_CashShopPurchaseExpChanged
LP_CashShopGachaponStampItemResult
LP_CashShopCheckTransferWorldPossibleResult
LP_CashShopMemberShopResult
LP_END_CASHSHOP
LP_BEGIN_FUNCKEYMAPPED
LP_FuncKeyMappedInit = @0114
LP_PetConsumeItemInit = @0115
LP_PetConsumeMPItemInit
LP_END_FUNCKEYMAPPED
LP_BEGIN_ITC
LP_ITCChargeParamResult
LP_ITCQueryCashResult
LP_ITCNormalItemResult
LP_END_ITC
LP_BEGIN_MAPLETV
LP_MapleTVUpdateMessage
LP_MapleTVClearMessage
LP_MapleTVSendMessageResult
LP_BroadSetFlashChangeEvent
LP_END_MAPLETV