LP_BEGIN_SOCKET
LP_CheckPasswordResult = @0001

LP_WorldInformation = @0003
LP_SelectWorldResult = @0004
LP_SelectCharacterResult = @0005
LP_CheckDuplicatedIDResult = @0006
LP_CreateNewCharacterResult = @0007
LP_DeleteCharacterResult = @0008
LP_MigrateCommand = @0009
LP_AliveReq = @000A
LP_AuthenCodeChanged = @000B
LP_AuthenMessage = @000C
LP_JMS_CheckGameGuardUpdatedResult = @000D

LP_SecurityPacket
# [reserved]
# [reserved]
# [reserved]
LP_CheckUserLimitResult = @0014
LP_END_SOCKET
LP_BEGIN_CHARACTERDATA
LP_InventoryOperation = @0018
LP_InventoryGrow = @0019
LP_StatChanged = @001A
LP_TemporaryStatSet = @001B
LP_TemporaryStatReset = @001C
LP_ChangeSkillRecordResult = @001D
LP_SkillUseResult = @001E
LP_GivePopularityResult = @001F
LP_Message = @0020
LP_MemoResult = @0021
LP_MapTransferResult = @0022
LP_AntiMacroResult = @0023
# [reserved]
LP_ClaimResult = @0025
LP_SetClaimSvrAvailableTime = @0026
LP_ClaimSvrStatusChanged = @0027
LP_SetTamingMobInfo = @0028
LP_QuestClear = @0029
LP_EntrustedShopCheckResult = @002A
LP_SkillLearnItemResult = @002B
# [reserved]
LP_CharacterInfo = @002D
LP_PartyResult = @002E
LP_FriendResult = @002F
# [reserved]
LP_GuildResult = @0031
LP_TownPortal = @0032
LP_BroadcastMsg = @0033
LP_IncubatorResult = @0034
LP_ShopScannerResult = @0035
LP_ShopLinkResult = @0036
LP_CashPetFoodResult = @0037
LP_SetWeekEventMessage = @0038
LP_SetPotionDiscountRate = @0039
# [reserved]
LP_ImitatedNPCResult = @003A
LP_ImitatedNPCData = @003B
LP_MonsterBookSetCard
LP_MonsterBookSetCover
LP_MacroSysDataInit
LP_END_CHARACTERDATA
LP_BEGIN_STAGE
LP_SetField = @0047
LP_SetCashShop = @0048
LP_END_STAGE
LP_BEGIN_FIELD
LP_TransferFieldReqIgnored = @004B
LP_TransferChannelReqIgnored = @004C
LP_FieldSpecificData = @004D
LP_GroupMessage = @004E
LP_Whisper = @004F
LP_MobSummonItemUseResult = @0050
LP_FieldEffect = @0051
LP_BlowWeather = @0052
LP_PlayJukeBox = @0053
LP_AdminResult = @0054
LP_Quiz = @0055
LP_Desc = @0056
LP_Clock = @0057
LP_CONTIMOVE = @0058
LP_CONTISTATE = @0059
LP_SetQuestClear = @005A
LP_SetQuestTime = @005B
LP_SetObjectState = @005C
LP_DestroyClock = @005D
LP_StalkResult
LP_BEGIN_USERPOOL
LP_UserEnterField = @0060
LP_UserLeaveField = @0061
LP_BEGIN_USERCOMMON
LP_UserChat = @0063
LP_UserADBoard
LP_UserMiniRoomBalloon
LP_UserConsumeItemEffect
LP_UserItemUpgradeEffect
LP_BEGIN_PET
LP_PetActivated = @006A
LP_PetTransferField = @006B
LP_PetMove = @006C
LP_PetAction = @006D
LP_PetNameChanged = @006E
LP_PetActionCommand = @006F
LP_END_PET
LP_BEGIN_SUMMONED
LP_SummonedEnterField = @0072
LP_SummonedLeaveField = @0073
LP_SummonedMove = @0074
LP_SummonedAttack = @0075
LP_SummonedSkill = @0076
LP_SummonedHit = @0077
LP_END_SUMMONED
LP_BEGIN_USERREMOTE
LP_UserMove
LP_UserMeleeAttack
LP_UserShootAttack
LP_UserMagicAttack
LP_UserBodyAttack
LP_UserSkillPrepare
LP_UserSkillCancel
LP_UserHit
LP_UserEmotion
LP_UserSetActiveEffectItem
LP_UserSetActivePortableChair
LP_UserAvatarModified
LP_UserEffectRemote
LP_UserTemporaryStatSet
LP_UserTemporaryStatReset
LP_UserHP
LP_UserGuildNameChanged
LP_UserGuildMarkChanged
LP_UserThrowGrenade
LP_END_USERREMOTE
LP_BEGIN_USERLOCAL
LP_UserSitResult
LP_UserEffectLocal
LP_UserTeleport
LP_Premium
LP_MesoGive_Succeeded
LP_MesoGive_Failed
LP_UserQuestResult
LP_NotifyHPDecByField
LP_UserPetSkillChanged
LP_UserBalloonMsg
LP_PlayEventSound
LP_PlayMinigameSound
LP_SkillCooltimeSet
LP_END_USERLOCAL
LP_END_USERPOOL
LP_BEGIN_MOBPOOL
LP_MobEnterField = @009D
LP_MobLeaveField = @009E
LP_MobChangeController = @009F
LP_BEGIN_MOB
LP_MobMove = @00A1
LP_MobCtrlAck = @00A2
LP_MobCtrlHint
LP_MobStatSet = @00A4
LP_MobStatReset = @00A5
LP_MobSuspendReset = @00A6
LP_MobAffected = @00A7
LP_MobDamaged = @00A8
LP_MobSpecialEffectBySkill
# [reserved]
LP_MobHPIndicator
LP_MobCatchEffect
LP_MobEffectByItem
LP_MobAttackedByMob
LP_END_MOB
LP_END_MOBPOOL
LP_BEGIN_NPCPOOL
LP_NpcEnterField = @00B1
LP_NpcLeaveField = @00B2
LP_NpcChangeController = @00B3
LP_BEGIN_NPC
LP_NpcMove = @00B5
LP_NpcSpecialAction = @00B6
#
#
LP_END_NPC
LP_BEGIN_NPCTEMPLATE
LP_NpcSetScript = @00BB
LP_END_NPCTEMPLATE
LP_END_NPCPOOL
LP_BEGIN_EMPLOYEEPOOL
LP_EmployeeEnterField = @00BF
LP_EmployeeLeaveField = @00C0
LP_EmployeeMiniRoomBalloon = @00C1
LP_END_EMPLOYEEPOOL
LP_BEGIN_DROPPOOL
LP_DropEnterField = @00C4
LP_DropLeaveField = @00C5
LP_END_DROPPOOL
LP_BEGIN_MESSAGEBOXPOOL
LP_CreateMessgaeBoxFailed = @00C8
LP_MessageBoxEnterField = @00C9
LP_MessageBoxLeaveField = @00CA
LP_END_MESSAGEBOXPOOL
LP_BEGIN_AFFECTEDAREAPOOL
LP_AffectedAreaCreated = @00CD
LP_AffectedAreaRemoved = @00CE
LP_END_AFFECTEDAREAPOOL
LP_BEGIN_TOWNPORTALPOOL
LP_TownPortalCreated = @00D1
LP_TownPortalRemoved = @00D2
LP_END_TOWNPORTALPOOL
LP_BEGIN_REACTORPOOL
LP_ReactorChangeState = @00D5
LP_ReactorMove
LP_ReactorEnterField = @00D7
LP_ReactorLeaveField = @00D8
LP_END_REACTORPOOL
LP_BEGIN_ETCFIELDOBJ
LP_SnowBallState
LP_SnowBallHit
LP_SnowBallMsg
LP_SnowBallTouch
LP_CoconutHit
LP_CoconutScore
LP_HealerMove
LP_PulleyStateChange
LP_MCarnivalEnter
LP_MCarnivalPersonalCP
LP_MCarnivalTeamCP
LP_MCarnivalResultSuccess
LP_MCarnivalResultFail
LP_MCarnivalDeath
LP_MCarnivalMemberOut
LP_MCarnivalGameResult
LP_ArenaScore
LP_ZakumTimer
LP_END_ETCFIELDOBJ
LP_BEGIN_SCRIPT
LP_ScriptMessage = @00ED
LP_END_SCRIPT
LP_BEGIN_SHOP
LP_OpenShopDlg = @00F0
LP_ShopResult = @00F1
LP_END_SHOP
LP_TrunkResult = @00F3
LP_BEGIN_STOREBANK
LP_StoreBankGetAllResult = @00F5
LP_StoreBankResult = @00F6
LP_END_STOREBANK
LP_RPSGame = @00F8
LP_Messenger = @00F9
LP_MiniRoom = @00FA
LP_BEGIN_TOURNAMENT
LP_Tournament
LP_TournamentMatchTable
LP_TournamentSetPrize
LP_TournamentNoticeUEW
LP_TournamentAvatarInfo
LP_END_TOURNAMENT
LP_BEGIN_WEDDING
LP_WeddingProgress
LP_WeddingCremonyEnd
LP_END_WEDDING
LP_BEGIN_JMS_PACHINKO
LP_END_JMS_PACHINKO
LP_Parcel = @0102
LP_END_FIELD
LP_BEGIN_CASHSHOP
LP_CashShopChargeParamResult
LP_CashShopQueryCashResult
LP_CashShopCashItemResult
LP_CashShopPurchaseExpChanged
LP_CashShopGachaponStampItemResult
LP_CashShopCheckTransferWorldPossibleResult
LP_CashShopMemberShopResult
LP_END_CASHSHOP
LP_BEGIN_FUNCKEYMAPPED
LP_FuncKeyMappedInit = @0114
LP_PetConsumeItemInit = @0115
LP_PetConsumeMPItemInit
LP_END_FUNCKEYMAPPED
LP_BEGIN_MAPLETV
LP_MapleTVUpdateMessage
LP_MapleTVClearMessage
LP_MapleTVSendMessageResult
LP_BroadSetFlashChangeEvent
LP_END_MAPLETV