CP_BEGIN_SOCKET
CP_CheckPassword = @0001
CP_AccountInfoRequest
CP_WorldInfoRequest = @0003
CP_SelectWorld = @0004
CP_LogoutWorld
CP_SelectCharacter = @0005
CP_MigrateIn = @0006
CP_CheckDuplicatedID = @0007
CP_CreateNewCharacter = @0008
CP_DeleteCharacter = @0009
CP_AliveAck = @000A
CP_ExceptionLog = @000B
CP_SecurityPacket
CP_CheckUserLimit = @0011
CP_END_SOCKET
CP_BEGIN_USER
CP_UserTransferFieldRequest = @0017
CP_UserTransferChannelRequest = @0018
CP_UserMigrateToCashShopRequest = @0019
CP_UserMove = @001A
CP_UserSitRequest = @001B
CP_UserPortableChairSitRequest = @001C
CP_UserMeleeAttack = @001D
CP_UserShootAttack = @001E
CP_UserMagicAttack = @001F
CP_UserHit = @0020
CP_UserChat = @0021
CP_UserADBoardClose
CP_UserActivateEffectItem = @0024
CP_UserMonsterBookSetCover
CP_UserSelectNpc = @0028
CP_UserScriptMessageAnswer = @0029
CP_UserShopRequest = @002A
CP_UserTrunkRequest
CP_UserEntrustedShopRequest
CP_ShopScannerRequest = @002F
CP_UserGatherItemRequest
CP_UserSortItemRequest
CP_UserChangeSlotPositionRequest = 0031
CP_UserStatChangeItemUseRequest = @0032
CP_UserStatChangeItemCancelRequest
CP_UserMobSummonItemUseRequest = @0035
CP_UserPetFoodItemUseRequest = @0036

CP_UserConsumeCashItemUseRequest = @0038
CP_UserBridleItemUseRequest
CP_UserSkillLearnItemUseRequest = @003A
CP_UserShopScannerItemUseRequest
CP_UserMapTransferItemUseRequest
CP_UserPortalScrollUseRequest = @003D
CP_UserUpgradeItemUseRequest = @003E
CP_UserAbilityUpRequest = @003F
CP_UserChangeStatRequest = @0040
CP_UserSkillUpRequest = @0041
CP_UserSkillUseRequest = @0042
CP_UserSkillCancelRequest = @0043
CP_UserSkillPrepareRequest = @0044
CP_UserDropMoneyRequest = @0045
CP_UserGivePopularityRequest
CP_UserCharacterInfoRequest = @0048
CP_UserActivatePetRequest = @0049
CP_UserTemporaryStatUpdateRequest = @004A
CP_UserPortalScriptRequest = @004B
CP_UserPortalTeleportRequest = @004C
CP_UserMapTransferRequest = @004D
CP_UserQuestRequest
CP_UserExpUpItemUseRequest
CP_UserTempExpUseRequest
CP_GroupMessage
CP_Whisper
CP_Messenger
CP_MiniRoom
CP_PartyRequest
CP_Admin
CP_Log
CP_FriendRequest
CP_FuncKeyMappedModified = @0063
CP_RPSGame
CP_MarriageRequest
CP_UserMigrateToITCRequest
CP_END_USER
CP_BEGIN_PET
CP_PetMove
CP_PetAction
CP_PetInteractionRequest
CP_PetDropPickUpRequest
CP_PetStatChangeItemUseRequest
CP_PetUpdateExceptionListRequest
CP_END_PET
CP_BEGIN_SUMMONED
CP_SummonedMove
CP_SummonedAttack
CP_SummonedHit
CP_SummonedSkill
CP_Remove
CP_END_SUMMONED
CP_BEGIN_FIELD
CP_BEGIN_LIFEPOOL
CP_BEGIN_MOB
CP_MobMove
CP_MobApplyCtrl
CP_MobDropPickUpRequest
CP_MobHitByObstacle
CP_MobHitByMob
CP_MobSelfDestruct
CP_END_MOB
CP_BEGIN_NPC
CP_NpcMove
CP_NpcSpecialAction
CP_END_NPC
CP_END_LIFEPOOL
CP_BEGIN_DROPPOOL
CP_DropPickUpRequest = @008A
CP_END_DROPPOOL
CP_BEGIN_REACTORPOOL
CP_ReactorHit
CP_ReactorTouch
CP_RequireFieldObstacleStatus
CP_END_REACTORPOOL
CP_BEGIN_EVENT_FIELD
CP_EventStart
CP_SnowBallHit
CP_SnowBallTouch
CP_CoconutHit
CP_TournamentMatchTable
CP_PulleyHit
CP_END_EVENT_FIELD
CP_CONTISTATE
CP_BEGIN_PARTY_MATCH
CP_INVITE_PARTY_MATCH
CP_CANCEL_INVITE_PARTY_MATCH
CP_END_PARTY_MATCH
CP_END_FIELD
CP_BEGIN_CASHSHOP
CP_CashShopChargeParamRequest
CP_CashShopQueryCashRequest
CP_CashShopCashItemRequest
CP_CashShopCheckCouponRequest
CP_CashShopGiftMateInfoRequest
CP_END_CASHSHOP
CP_BEGIN_ITC
CP_ITCChargeParamRequest
CP_ITCQueryCashRequest
CP_ITCItemRequest
CP_END_ITC
CP_BEGIN_MAPLETV
CP_MapleTVSendMessageRequest
CP_MapleTVUpdateViewCount
CP_END_MAPLETV
