LP_BEGIN_SOCKET
LP_CheckPasswordResult = @0000
LP_AccountInfoResult = @0001
LP_WorldInformation = @0002
LP_SelectWorldResult = @0003
LP_SelectCharacterResult = @0004
LP_CheckDuplicatedIDResult = @0005
LP_CreateNewCharacterResult = @0006
LP_DeleteCharacterResult = @0007
LP_MigrateCommand = @0008
LP_AliveReq = @0009
LP_AuthenCodeChanged = @000A
LP_AuthenMessage = @000B
LP_SecurityPacket = @000C
LP_JMS_GuardInspectProcess = @000D
LP_JMS_CheckGameGuardUpdatedResult = @000E
LP_EnableSPWResult = @000F
LP_DeleteCharacterOTPRequest = @0010
LP_CheckSPWResult = @0011
LP_END_SOCKET
LP_BEGIN_CHARACTERDATA
LP_InventoryOperation = @0012
LP_InventoryGrow = @0013
LP_StatChanged = @0014
LP_END_CHARACTERDATA
LP_BEGIN_STAGE
LP_SetField = @0040
LP_SetCashShop = @0041
LP_END_STAGE
LP_BEGIN_MAP
LP_SetBackgroundEffect = @0042
LP_ClearBackgroundEffect = @0043
LP_END_MAP