# tacos
ip = 127.0.0.1
port.login = 8484
port.channel = 8500
port.cashshop = 8600
port.itc = 8601

# database
database.host = 127.0.0.1
database.port = 3306
database.user = root
database.password =

# sub settings
login.userlimit = 100
login.antihack = false